//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج با موفقیت.
        /// </summary>
        public static string Account_Logout_Success {
            get {
                return ResourceManager.GetString("Account_Logout_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی در اجرای درخواست شما رخ داده است.
        /// </summary>
        public static string CatchError {
            get {
                return ResourceManager.GetString("CatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محتوای وارد شده یافت نشد.
        /// </summary>
        public static string InvalidContent {
            get {
                return ResourceManager.GetString("InvalidContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسخه وارد شده صحیح نمی باشد..
        /// </summary>
        public static string InvalidMagzineVersion {
            get {
                return ResourceManager.GetString("InvalidMagzineVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر یافت نشد.
        /// </summary>
        public static string InvalidUser {
            get {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا.
        /// </summary>
        public static string Login_BadRequest {
            get {
                return ResourceManager.GetString("Login_BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود با موفقیت انجام شد.
        /// </summary>
        public static string Login_SuccessLogin {
            get {
                return ResourceManager.GetString("Login_SuccessLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل وارد شده صحیح نمی باشد..
        /// </summary>
        public static string MobilExpersionValidation {
            get {
                return ResourceManager.GetString("MobilExpersionValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد فعال سازی صحیح نمی باشد.
        /// </summary>
        public static string Registe_WrongActivationCode {
            get {
                return ResourceManager.GetString("Registe_WrongActivationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل شما تکراری می باشد.
        /// </summary>
        public static string Register_DuplicateCellNumber {
            get {
                return ResourceManager.GetString("Register_DuplicateCellNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دفعات درخواست کد فعال سازی محدود شد.
        /// </summary>
        public static string Register_ResendActivationCodeLimit {
            get {
                return ResourceManager.GetString("Register_ResendActivationCodeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اکشن با موفقیت انجام شد.
        /// </summary>
        public static string Register_Success {
            get {
                return ResourceManager.GetString("Register_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری با موفقیت فعال شد.
        /// </summary>
        public static string Register_SuccessActivate {
            get {
                return ResourceManager.GetString("Register_SuccessActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد فعال سازی مجدادا ارسال گردید.
        /// </summary>
        public static string Register_SuccessResendCode {
            get {
                return ResourceManager.GetString("Register_SuccessResendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر با موفقیت از دیتابیس حذف شد.
        /// </summary>
        public static string Success_DeleteUser {
            get {
                return ResourceManager.GetString("Success_DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازیابی اطلاعات با موفقیت انجام شد.
        /// </summary>
        public static string SuccessGet {
            get {
                return ResourceManager.GetString("SuccessGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات با موفقیت ثبت گردید.
        /// </summary>
        public static string SuccessPost {
            get {
                return ResourceManager.GetString("SuccessPost", resourceCulture);
            }
        }
    }
}
